/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OrderImport } from './routes/order'
import { Route as ListImport } from './routes/list'
import { Route as CartImport } from './routes/cart'
import { Route as IndexImport } from './routes/index'
import { Route as ListIdImport } from './routes/list_.$id'

// Create/Update Routes

const OrderRoute = OrderImport.update({
  path: '/order',
  getParentRoute: () => rootRoute,
} as any)

const ListRoute = ListImport.update({
  path: '/list',
  getParentRoute: () => rootRoute,
} as any)

const CartRoute = CartImport.update({
  path: '/cart',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ListIdRoute = ListIdImport.update({
  path: '/list/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cart': {
      preLoaderRoute: typeof CartImport
      parentRoute: typeof rootRoute
    }
    '/list': {
      preLoaderRoute: typeof ListImport
      parentRoute: typeof rootRoute
    }
    '/order': {
      preLoaderRoute: typeof OrderImport
      parentRoute: typeof rootRoute
    }
    '/list/$id': {
      preLoaderRoute: typeof ListIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  CartRoute,
  ListRoute,
  OrderRoute,
  ListIdRoute,
])

/* prettier-ignore-end */
